### ISSUE TITLE
[CM12.1] broken 'build.mk'

### ISSUE THREAD

**Issue by galexite** [lenovo-a3-dev/android_device_lenovo_a3#4]
The 'build.mk' does not successfully apply the MediaTek header to the kernel or ramdisk and therefore the system or recovery will not boot. In the meanwhile, the solution would be to manually pack the kernel and ramdisk using another method or tool.

**Comment by Incredible-O** [comment]
The makefile is fine and works for me (and many other MTK devices) - it has only been tested on cm-11.0 though (there is no cm-12.1 branch), but should work on cm-12.1 too.

**Comment by galexite** [comment]
Sorry – I do apologise. The issue is not with the build.mk file; instead,
it's with CM12.
